require: rubocop-rspec

Metrics/LineLength:
  Max: 95
Style/Documentation:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Rails/HttpPositionalArguments:
  Enabled: false

# Rails exceptions
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
